### PR TITLE
Create index proposal

### PR DESCRIPTION
**Pull request by ericmartinezr**
This is a proposal for the index of Community FAQ for making it more readable and have an order

### CODE REVIEW

**Comment by ericmartinezr** [comment]
pls review, add your thoughts

**Comment by escardin** [comment]
Looks reasonable. I was just thinking the FAQ had become a little unwieldy. I think I'd double link some of the fun stuff in Rx as well. It needs lots of examples. I'll see about working on reorganising soon.

**Comment by ericmartinezr** [comment]
:+1:

**Comment by ericmartinezr** [comment]
Uhmmm... @escardin I don't know what I did really, I was playing in my fork, then pushed everything, I didn't mean to merge this. Please revert all if I screwed up something..

**Pull request merged**
