### PR TITLE
WIP best practices

### PR DESCRIPTION
**Pull request by ericmartinezr**
DO NOT MERGE
- [x] Proper use of EventEmitters
- [x] ElementRef, nativeElement and Renderer
- [ ] Don't use Subjects (or just a little)
- [x] Don't mix angular2 with 3rd libs
- [x] Don't use `ngAfterViewChecked` nor `ngAfterContentChecked`
- [x] Accessing elements in the view
- [x] Using @Injectable() in every service
- [x] DynamicComponentLoader and loadAsRoot

Follow up of https://github.com/escardin/angular2-community-faq/issues/18

### CODE REVIEW

**Comment by ericmartinezr** [comment]
@escardin could you take the Subjects one? I don't really understand why they're so bad.

**Comment by escardin** [comment]
Sure. I may pester rob for some links again, but I'll write something up next time I'm waiting on deploys.

**Comment by ericmartinezr** [comment]
@escardin @brandonroberts please review. I'm still short in some explanations, can't think of how to improve them, ideas, sources?

**Comment by escardin** [comment]
This is great! I'd like to clean up the language a little bit. I think you're right some of the explanations are a little basic. I'm not sure how I would improve on them yet.

**Comment by ericmartinezr** [comment]
@escardin please! Fix my english :P I would really appreciate that, like seriously. I will keep this open until we have some more info on those subjects or we merge it already and we modify when we have that info?

**Comment by escardin** [comment]
I just stumbled upon rob talking about subject in the gitter history. Someone had a link that they wanted clarification on regarding subjects.

**Comment by escardin** [comment]
Since this is just a faq, I'm generally of the opinion of merge once the content is cleaned up, and fill in gaps later.

**Comment by escardin** [comment]
article on subjects: http://tomstechnicalblog.blogspot.ca/2016/03/rxjava-problem-with-subjects.html Will use this and possibly others as a basis for why not to (ab)use subjects

**Comment by ericmartinezr** [comment]
Using `@Injectable()` in every service (see https://github.com/angular/angular.io/pull/1012#issuecomment-202326319). Explain that it's only for TypeScript to emit metadata, point to Pascal's article.

**Comment by escardin** [comment]
another article on not using subjects http://davesexton.com/blog/post/To-Use-Subject-Or-Not-To-Use-Subject.aspx

**Comment by escardin** [comment]
https://medium.com/@benlesh/learning-observable-by-building-observable-d5da57405d87#.12a0rfxtt
https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339#.x0q63ntrm

**Comment by ericmartinezr** [comment]
Don't use `DynamicComponentLoader#loadAsRoot` at least we are rewriting the bootstrap logic.

**Comment by ericmartinezr** [comment]
@escardin you can review it when you have time. You said you would fix some englis stuff :P, feel free to add comments where something must be improved. Also if you think something should be removed until we have more info on the subject let me know.

With all that I think this could be merged, I added a message on the top of the section "Section still not complete. Work in progress", so we can fix it/improve it with time. What do you think?

**Comment by escardin** [comment]
I'll try and look tonight. I think as a faq it's always being expanded, so having sections in the contents that don't have links might be enough to say we haven't filled it in yet.

**Pull request merged**
