### PR TITLE
chore(faq): Added dedicated router section

### PR DESCRIPTION
**Pull request by brandonroberts**

### CODE REVIEW

**Comment by brandonroberts** [comment]
@escardin @ericmartinezr Please review

**Comment by ericmartinezr** [comment]
Beautiful :clap: :clap: :clap:

**Edit**

Can we add 
- Adding dynamic config
- Using regex

I have a few answers that you can copy & paste to make it easier, or improve them [#1](http://stackoverflow.com/q/36207023/4933038), [#2](http://stackoverflow.com/q/36191823/4933038), [#3](http://stackoverflow.com/a/35997976/4933038)

**Comment by escardin** [comment]
Awesome! Do you want this merged or do you want to wait?

**Comment by brandonroberts** [comment]
I'll add a few more answers, then it can be merged.

**Comment by brandonroberts** [comment]
Ok, this PR is ready for final review

**Comment by ericmartinezr** [comment]
@brandonroberts Thanks a lot for helping! Beautiful work!

**Pull request merged**
